mysql:
  kit:
    host: localhost
    port: 3306
    username: root
    password: root
    database: root
  rank:
    host: localhost
    port: 3306
    username: root
    password: root
    database: root
